packages:
  - "apps/*"
  - "packages/*"
  - "services/*"
  - "tooling/*"

catalog:
  "@prisma/client": ^5.21.1
  "@tanstack/react-query": ^5.59.15
  "@ts-rest/core": ^3.51.0
  "@ts-rest/react-query": ^3.50.0
  "@types/node": ^20.16.11
  dotenv: ^16.3.1
  eslint: ^9.12.0
  fastify: ^5.0.0
  prettier: ^3.3.3
  prisma: ^5.21.1
  tailwindcss: ^3.4.14
  tailwindcss-animate: ^1.0.7
  tsx: ^4.7.1
  typescript: ^5.9.3
  zod: ^3.24.2